# Source: fluentbit-resource/templates/fluentbit/outputs.yaml
# Elasticsearch index  in taco-es
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fbcr-taco-taco-es-syslog
  namespace: lma
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "syslog.*"
  es:
    index: syslog
    host: eck-elasticsearch-es-http
    port: 9200
    type: syslog
    httpUser:
      valueFrom:
        secretKeyRef:
          name: fluentbit-es-user-taco-es
          key: username
    httpPassword:
      valueFrom:
        secretKeyRef:
          name: fluentbit-es-user-taco-es
          key: password
    tls:
      verify: false
